### ISSUE TITLE
Download Data in Desktop

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#35]
In desktop, the 'Share map DATA' button downloads the data (in mobile devices opens the navigator.share menu ).

**Comment by acholyn** [comment]
whilst I've enabled this functionality, it doesn't seem to be in the same format as the original uploaded file because it doesn't work with the map to display markers. Is this expected or not? i.e should it also be usable with the map to display markers or is that not the intended use of the downloaded file

**Comment by MarcosMoreu** [comment]
simply download the map data as geojson file when the "Share map DATA" is clicked on Desktop
