### ISSUE TITLE
Hide homescreen when export

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#94]
When chat exported from WhatsApp, the homescreen appears for 1-2 secs before the gif appears. Can we make it so only the gif is shown?

**Comment by acholyn** [comment]
my suggestion for the solution to this would be to set the loader as the initial thing that happens when you load the site regardless of if it's from the export or the browser, or possibly we have to set the menu not to show initially and then display it (after the window loads?) possibly fading it in?
the issue is due to the menu being visible when the app is initialised
let me know what you think

**Comment by acholyn** [comment]
to try: adding the loader as the initial thing when loading or exporting
