### ISSUE TITLE
Design of Login/Data upload Menu

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#96]
Currently is only Phone number. We need to have two different designs depending on whether the user opens the menu from the burger or from the 'upload data' button. 

- For the burger: Phone number 
- For the 'upload data': Phone number & Campaign code (6-digit code generated with Kapta Web) & Open Data text. We want to support the option of submitting as open data. One easy approach for now would be to include a text (below the 'Campaign Code' box) saying: "Enter your private campaign code if you have one. If you want to upload your data as open data, type 'opendata' in the 'Campaign box'. Click here to know more about OPEN DATA in Kapta". Next to this text we can include a little button 'ℹ️' that opens an information page (we still need to figure out what we write there: consent, legal disclaimer etc etc).

Thoughts???

**Comment by acholyn** [comment]
All sounds fine to me. Regarding the implementation, we'll use the task table to get the code and display the title/description so they can be sure it's the right one. If we want to do a catch-all with the opendata, shall I set up the task table so whenever it's created it will have an entry for this? 

Might want to think about whether we want to assign it to a userid

**Comment by MarcosMoreu** [comment]
Yeah, good point about displaying info.
Let's discuss in our next meeting what's the best approach for the open data. It might be better (in terms of data security issues) that the user needs to enter a code rather than only selecting 'open data'? 

As for assigning it to a userid, do you mean whether the open data contributions should be anonymous? All contributions (private & open) must the associated to a phone number/userid.

**Comment by acholyn** [comment]
didn't mean anonymous. I've set it for now to have "opendata" as the userID in the task table but should be able to set it as the one from the cognito pool when we create it, that would then mean that we have to initialise the cognito pool before the dynamodb tables (which is fine but important to know). Would it make sense to put the cognito creation in the same stack creation as the dynamo tables or do we want to keep them separate? 🤔

**Comment by acholyn** [comment]
we presently have a metadata form for when a registered user clicks the upload button (this may not be functional atm), do we want to update the flow so that 1. if not logged in, they're shown the login dialog and then 2. once logged in shown the campaign code input and then 3. shown the form for the metadata? or combine 2 and 3 into one form but require the campaign code for submission?

**Comment by tcouch** [comment]
So, can we just confirm users should not be able to upload data without first logging in (because uploaded datasets have to have a kapta mobile user ID associated with them)?

I think then the third option on the sharing options menu accessible from the map display, should say something like "log in to upload data" if the user is not already logged in. If the user clicks that button, they're shown the login dialog and, if successful, the button changes to "upload data"

It then seems like the metadata dialog where we ask users for a topic and goal is redundant in the case where they're responding to a specific task since presumably we already know this. So it makes sense to me to ask for the 6-digit task code first. Perhaps the initial dialog when users select upload data could have an input form for a task code and a submit button. While the input box is empty, the button text reads "upload data for public use", but changes to "submit to task" once the code is entered. The following dialog then either:
* Displays the task metadata and asks the user to confirm before uploading
* Or, if it's a public submission, displays the metadata form where it asks for topic, goal, consent etc.

@MarcosMoreu @acholyn thoughts?

**Comment by tcouch** [comment]
Here's a mock up of what it could look like
![Image](https://github.com/user-attachments/assets/d3a32dda-64d8-46a1-8f6d-502f54938300)

**Comment by acholyn** [comment]
ooh I do like the button for the open data option. This looks good to me

**Comment by MarcosMoreu** [comment]
Yeah. Really like it. Only thing is that I'd remove the 'Goal' box and put "University College London's Kapta team" instead "Kapta".
We will also need a little button e.g. i icon, that takes the users to another page with detailed information about data protections, ethics etc....

Yes, users can only submit data (both private and open) if they're logged in. Agree that if the user is already logged in (in current session or in previous ones, i.e. we need to store this in the local storage), the share button should should directly the UI that Tom created (the one on the left)

**Comment by acholyn** [comment]
can we close this? We can open a new issue for fine tuning the blurb
